import type { NextPage } from 'next';

import Head from 'next/head';

import Header from 'components/header/header';

import styles from './signup.module.scss';

const SignUpPage: NextPage = () => {
	return (
		<div>
			<Header />

			<Head>
				<title>Bank API - Sign up</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.main}>Sign up</div>
		</div>
	);
};

export default SignUpPage;
