import type { NextPage } from 'next';

import Head from 'next/head';

import Header from 'components/header/header';

import styles from './signin.module.scss';

const SignInPage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Bank API - Sign in</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<div className={styles.main}>Sign in</div>
		</div>
	);
};

export default SignInPage;
