import React from 'react';
import type { NextPage } from 'next';

import Head from 'next/head';
import Link from 'next/link';

import Header from 'components/header/header';

import styles from './signup.module.scss';

const SignInPage: NextPage = () => {
	return (
		<React.Fragment>
			<Head>
				<title>Bank API - Sign up</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<div className={styles.main}>
				<div className={styles.sign_up}>
					<h1>Sign up</h1>
					<span>Псевдоним</span>
					<input type="text" placeholder="John Doe" />
					<span>Логин</span>
					<input type="text" placeholder="example@mail.ru" />
					<span>Пароль</span>
					<input type="password" placeholder="******" />
					<span>Повторите пароль</span>
					<input type="password" placeholder="******" />
					<Link href="/" className={styles.btn}>
						Sign up
					</Link>
					<p>
						* Нажимая продолжить, вы соглашаетесь с нашими Условиями
						предоставления услуг и Политикой конфиденциальности .
					</p>
				</div>
			</div>
		</React.Fragment>
	);
};

export default SignInPage;
